# fly.toml app configuration file generated for django-formset-quiet-waterfall-43 on 2024-04-04T14:00:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'django-formset'
primary_region = 'ams'
console_command = '/web/manage.py shell'

[build]
  dockerfile = ".deployment/Dockerfile"

[mounts]
  source = 'workdir'
  destination = '/web/workdir'

[env]
  PORT = '8080'
  DJANGO_WORKDIR = '/web/workdir'
  DJANGO_MEDIA_ROOT = '/web/workdir/media'
  DJANGO_STATIC_ROOT = '/web/staticfiles'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/web/static'
  url_prefix = '/static/'
